### ISSUE TITLE
Vendors & Captain lists should be alphabetical

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#274]
With so many vendors and captains, it would really help for these pull down menus to be alphabetical.  

Currently, both lists appear pretty random.

**Comment by babybunny** [comment]
done

**Comment by caripang** [comment]
https://rebuildingtogethercaptain.appspot.com/room/order_reconcile/3032
apparently, the vendor list for reconciling orders still appears to be random.  It would be helpful to have it be alphabetized.
