### ISSUE TITLE
Rooms Captain site view - shows all historically assigned sites 

### ISSUE THREAD

**Issue by billyrtp** [babybunny/rebuildingtogethercaptain#508]
When Captains login they see all sites they have ever been assigned to in the system. We need to change the view so when they login, they only see this year's site.

**Comment by babybunny** [comment]
We should restrict to active Programs by default and then give a way to see the sites in the Inactive Programs as well.

**Comment by caripang** [comment]
Please let us know if there is a way to indicate which are active or
inactive, or I don't know if there's a way to create start/end dates to
help with that so any projects that a Captain sees would be in order of
when they most recently started the project?

**Comment by babybunny** [comment]
You can see the active / inactive ones here
https://console.cloud.google.com/datastore/entities;kind=Program;ns=__$DEFAULT$__;sortCol=name;sortDir=DESCENDING/query/kind?project=rebuildingtogethercaptain-hrd

Basically all Programs from 2017 to present are Active.

I think we can edit them directly in the datastore but there are no screens built to manage Programs.

**Comment by billyrtp** [comment]
If I'm understanding you correctly I think we should make NRD 2018 and NRD
2017 inactive to restrict the Captains view for sites from those years.
This should prevent site confusion when the captains login.

Billy Hoover | Manager, Operations & Impact


Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x221 | (F): 650.366.9053
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*Repairing Homes. Revitalizing Communities. Rebuilding Lives.*


* <https://www.facebook.com/RebuildingTogetherPeninsula>
<https://www.instagram.com/rtpeninsula/>
<https://twitter.com/RTPeninsula>
<https://www.youtube.com/user/RTPeninsula>*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street
<https://maps.google.com/?q=852+Charter+Street&entry=gmail&source=g>,
between Bay & Spring.

**Comment by billyrtp** [comment]
Hi Luke,

It looks like captains when they login are still seeing old sites they were
assigned to and they are being merged into one long page (see attachment
below). Are you able to modify the view so that Captains only see their
current site?

Billy Hoover | Manager, Operations & Impact


Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x221 | (F): 650.366.9053
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*Repairing Homes. Revitalizing Communities. Rebuilding Lives.*


* <https://www.facebook.com/RebuildingTogetherPeninsula>
<https://www.instagram.com/rtpeninsula/>
<https://twitter.com/RTPeninsula>
<https://www.youtube.com/user/RTPeninsula>*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street
<https://maps.google.com/?q=852+Charter+Street&entry=gmail&source=g>,
between Bay & Spring.

**Comment by babybunny** [comment]
I just set all the Programs before 2019 to "Inactive".  That should fix it.

**Comment by billyrtp** [comment]
Thanks Luke!

Billy Hoover | Manager, Operations & Impact


Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x221 | (F): 650.366.9053
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*Repairing Homes. Revitalizing Communities. Rebuilding Lives.*


* <https://www.facebook.com/RebuildingTogetherPeninsula>
<https://www.instagram.com/rtpeninsula/>
<https://twitter.com/RTPeninsula>
<https://www.youtube.com/user/RTPeninsula>*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street
<https://maps.google.com/?q=852+Charter+Street&entry=gmail&source=g>,
between Bay & Spring.

**Comment by billyrtp** [comment]
Hi Luke,

Captains are reporting that they are still seeing all of their old
projects. Is there another route we can go to isolate so they can see only
this year's project?

Billy Hoover | Manager, Operations & Impact


Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x221 | (F): 650.366.9053
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*Repairing Homes. Revitalizing Communities. Rebuilding Lives.*


* <https://www.facebook.com/RebuildingTogetherPeninsula>
<https://www.instagram.com/rtpeninsula/>
<https://twitter.com/RTPeninsula>
<https://www.youtube.com/user/RTPeninsula>*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street
<https://maps.google.com/?q=852+Charter+Street&entry=gmail&source=g>,
between Bay & Spring.

**Comment by caripang** [comment]
Example: 

pyribar@gene.com, using Google Chrome browser

Sent this link: https://rebuildingtogethercaptain.appspot.com/room/site/view/5826567573864448/
What he saw: https://rebuildingtogethercaptain.appspot.com/room/site/view/1688230/
(but it may be that he was seeing his captain home page and didn't scroll down....)

What we'd prefer is for captain's to be able to see individual site pages instead of them all stacked together on one page.

**Comment by babybunny** [comment]
I made a test captain account and I can see the issue. 

I flushed the memcache and it did nothing.

**Comment by caripang** [comment]
It would also help if the order of the sites that they see at the top were sorted by site # in descending order (from the biggest site number (190... down to 110....))

The random order is also throwing the captains off.

**Comment by babybunny** [comment]
OK I got it fixed and verified with my test captain account.  Now we are only showing the sites in 2019 ("active") programs.  we can do the navigation features to older sites in the future.

**Comment by billyrtp** [comment]
Thanks so much Luke! We tested also with Cari's account and it looks to be
working.

Billy Hoover | Manager, Operations & Impact


Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x221 | (F): 650.366.9053
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*Repairing Homes. Revitalizing Communities. Rebuilding Lives.*


* <https://www.facebook.com/RebuildingTogetherPeninsula>
<https://www.instagram.com/rtpeninsula/>
<https://twitter.com/RTPeninsula>
<https://www.youtube.com/user/RTPeninsula>*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street
<https://maps.google.com/?q=852+Charter+Street&entry=gmail&source=g>,
between Bay & Spring.

**Comment by babybunny** [comment]
added this fix to nrd2019 branch.
